[project]
name = "plagiarism"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.0",
    "flask-sqlalchemy>=3.1",
    "scikit-learn>=1.3",
    "requests>=2.31"
]
